baseurl = "https://suzukeh.github.io/mypage"
languageCode = 'ja-jp'
title = 'すずき、すずけ、Suzuke'
theme = "papermod"
canonifyurls = true
paginate = 6
publishDir = "docs"
hasCJKLanguage = true
enableEmoji = true
enableGitInfo = true


[outputs]
    home = [ "HTML", "RSS", "JSON" ]

[params]
    env = "production"
    title = 'すずき、すずけ、Suzuke'
    description = "This is suzuke's page"
    author = "suzuke"
    ShowShareButtons = true
    dateformat = "2006/01/02"
    defaultTheme = "auto"
    ShowCodeCopyButtons = true
    ShowToc = true
    ShowBreadCrumbs = true
    ShowPostNavLinks = true
    images = ['https://raw.githubusercontent.com/Suzukeh/mypage/main/static/img/card.png']

        [params.homeInfoParams]
        Title = "suzuke (鈴木) のサイト"
        Content = """
ここはsuzukeのページです。
- GitHub Pagesを使ってみたかっただけなので、これ作った段階でほぼやりたいことは終わりました。
- 果たして更新はあるのか!?　乞うご期待。
        """

        [[params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/suzukeh1"

        [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Suzukeh"

        [[params.socialIcons]]
        name = "RSS"
        url = "index.xml"

[taxonomies]

    tag = "tags"
    series = "series"

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true

[markup.goldmark.renderer]
unsafe= true


        [[menu.main]]
        name = "Archive"
        url = "archives"
        weight = 5

       #[[menu.main]]
       #identifier = "categories"
       #name = "categories"
       #url = "categories/"
       #weight = 10

        [[menu.main]]
        identifier = "tags"
        name = "tags"
        url = "tags/"
        weight = 10

        [[menu.main]]
        identifier = "search"
        name = "search"
        url = "search/"
        weight = 20

